version: "3.9"

services:
  app:
    build: .
    ports:
      - "443:8123"
    volumes:
      - ./books:/app/books
      - ./epubs:/app/epubs
      - ./certs:/app/certs:ro
    environment:
      - PYTHONUNBUFFERED=1
    command: uvicorn server:app --host 0.0.0.0 --port 8123 --ssl-keyfile /app/certs/reader3.key --ssl-certfile /app/certs/reader3.crt
    restart: unless-stopped
